<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuiteForDataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b160af5b-f05e-4e84-8136-67c038eeb850</testSuiteGuid>
   <testCaseLink>
      <guid>6544b091-f20f-4b21-bf58-376ea81837da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenTest</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3b470ae9-b8c2-4172-b373-a2deeb337e63</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataOne</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>3b470ae9-b8c2-4172-b373-a2deeb337e63</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>114f6f50-e12c-471d-8e92-773060a0427f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3b470ae9-b8c2-4172-b373-a2deeb337e63</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>622fb356-2efc-4592-9d69-cc5c231f6851</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
